spring:
  # db 설정
  datasource:
    url: jdbc:mysql://localhost:3306/market_consumer?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dksthddl

  # jpa 설정
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate :
        format_sql : true
    database: mysql
  profiles:
    include: oauth
app:
  host: http://localhost:8084
server:
  port: 8086
email:
  admin:
    account: certification0test@gmail.com
    password: PCMmanager!