spring:
  # db 설정
  datasource:
    url: jdbc:mysql://localhost:3306/market?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: market
    password: market
#    password: ENC(ngEt6S/2mhKV2F30Wogksg==)

  # jpa 설정
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate :
        format_sql : true
    database: mysql
  profiles:
    include: oauth

app:
  host: http://localhost:8086
server:
  port: 8086
email:
  admin:
    account: certification0test@gmail.com
    password: END(GdWyNDQs0S10hpfizKtLSVb5irexBOKm)
#    password: PCMmanager!
jasypt:
  encryptor:
    bean: jasyptStringEncryptor