spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: c1ba1f09ecd07ec2d41685d595cf8f15
            client-secert: hZZUJawJxIHACvlIOG8yQFHWMUR9D2FB
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            redirect-uri: "http://localhost:8086/login/oauth2/code/kakao"
            scope:
              - profile
            client-authentication-method: POST
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
oauth2:
  social:
    kakao:
      base-url: https://kauth.kakao.com/oauth/authorize
      client-id: c1ba1f09ecd07ec2d41685d595cf8f15
      client-secret: hZZUJawJxIHACvlIOG8yQFHWMUR9D2FB
      token-url: https://kauth.kakao.com/oauth/token
      callback-url: http://localhost:8086/auth/kakao/callback
      user-info-url: https://kapi.kakao.com/v2/user/scopes