oauth2:
  social:
    kakao:
      base-url: https://kauth.kakao.com/oauth/authorize
      client-id: c1ba1f09ecd07ec2d41685d595cf8f15
      client-secret: hZZUJawJxIHACvlIOG8yQFHWMUR9D2FB
      token-url: https://kauth.kakao.com/oauth/token
      callback-url: http://localhost:8086/auth/kakao/callback
      user-info-url: https://kapi.kakao.com/v2/user/scopes